/**
 * 
 */
package enums;

/**
 * @author Marcos Lucas
 *
 */
public enum CursoGraduacao {

	ADMINISTRACAO, CIENCIA_DA_COMPUTACAO, DIREITO, ENGENHARIA_ELETRICA,
	ENGENHARIA_ESPACIAL, ENGENHARIA_MECATRONICA, MATEMATICA, MEDICINA,
	NUTRICAO, ODONTOLOGIA, PSICOLOGIA, VETERINARIA
}
